enableTelemetry: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-tsconfig-references.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-tsconfig-references.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

preferInteractive: true

npmPublishRegistry: "http://192.168.10.52:5050/api/packages/sozdev/npm/"
npmAuthToken: d478e523fe0a0b5200e75f90b06d659b80f52dd4

npmScopes:
  sozdev:
    npmRegistryServer: "http://192.168.10.52:5050/api/packages/sozdev/npm/"

unsafeHttpWhitelist:
  - "192.168.10.52"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
