name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: local
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Enable corepack
        run: corepack enable

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

  typecheck:
    runs-on: local
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Enable corepack
        run: corepack enable

      - name: Install
        run: yarn

      - name: Typecheck
        run: yarn typecheck
