name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT


      - uses: actions/cache@v3
        with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: ${{ steps.yarn-cache-dir-path.outputs.dir }}


      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Publish package
        run: yarn release
