version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:20

    command: tail -f /dev/null

    ports:
      - 3000:3000

    environment:
      - NODE_ENV=development
      - PORT=3000

    volumes:
      - ../..:/workspaces:cached

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  redis-data:
