version: '3.8'
services:
  devcontainer:
    image: gitea.local/sozdev/devcontainer-ts
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
  redis-data:
